# Generated by Django 3.1.4 on 2021-01-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
