# Generated by Django 3.1.4 on 2021-01-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_introduction_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=90000)),
                ('link_detail', models.TextField(max_length=90000, null=True)),
            ],
            options={
                'db_table': 'facebook_links',
            },
        ),
    ]
