# Generated by Django 3.1.4 on 2021-01-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20210102_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebooklink',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='facebooklink',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
