# Generated by Django 3.1.4 on 2021-01-02 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_auto_20210102_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerAfterMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=900000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prayer_after_mass',
            },
        ),
        migrations.AlterModelOptions(
            name='facebooklink',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='facebooklink',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='date_created',
        ),
        migrations.AddField(
            model_name='facebooklink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebooklink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='introduction',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
