# Generated by Django 3.1.4 on 2021-01-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_auto_20210102_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
