# Generated by Django 3.1.4 on 2021-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_auto_20210102_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideMisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=900000, null=True)),
                ('url_detail', models.TextField(max_length=900000, null=True)),
                ('position', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_misa',
            },
        ),
    ]
