# Generated by Django 3.1.4 on 2021-01-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_introduction_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='copywrite',
            field=models.TextField(max_length=90000, null=True),
        ),
    ]
