# Generated by Django 3.2.5 on 2021-07-31 16:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_youtubemass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfressionTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_confression', tinymce.models.HTMLField()),
                ('content_confression', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'confression_time',
            },
        ),
    ]
