# Generated by Django 3.2.5 on 2021-07-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_confressiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='confressiontime',
            name='content_adoration',
            field=models.TextField(max_length=90000, null=True),
        ),
        migrations.AlterField(
            model_name='confressiontime',
            name='calendar_confression',
            field=models.TextField(max_length=90000, null=True),
        ),
        migrations.AlterField(
            model_name='confressiontime',
            name='content_confression',
            field=models.TextField(max_length=90000, null=True),
        ),
    ]
