# Generated by Django 3.2.5 on 2021-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_masstime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedChurch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=900000, null=True)),
                ('logo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('church_url', models.TextField(max_length=90000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'linked_church',
            },
        ),
    ]
