# Generated by Django 3.2.5 on 2021-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_linkedchurch'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklink',
            name='file_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
