# Generated by Django 3.2.5 on 2021-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_alter_facebooklink_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklink',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
