# Generated by Django 3.2.5 on 2021-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_activityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=90000)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ('-created_at',),
            },
        ),
    ]
